name: odds_fetcher
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  sqflite_common_ffi: ^2.3.1
  sqflite: ^2.3.3+1
  intl: ^0.19.0
  path: ^1.8.3
  path_provider: ^2.1.3
  http: ^1.1.0
  pluto_grid: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  ffigen: ^17.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/odds_fetcher_template.db
    - assets/migrations/0001.sql
    - assets/migrations/0002.sql
    - assets/migrations/0003.sql
    - assets/migrations/0004.sql
    - assets/images/logo.jpg
