ALTER TABLE Filters ADD COLUMN filterHomeTeams INTEGER NOT NULL DEFAULT 1;
ALTER TABLE Filters ADD COLUMN filterAwayTeams INTEGER NOT NULL DEFAULT 1;
ALTER TABLE Filters ADD COLUMN pivotFilterHomeTeams INTEGER NOT NULL DEFAULT 1;
ALTER TABLE Filters ADD COLUMN pivotFilterAwayTeams INTEGER NOT NULL DEFAULT 1;
